apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: eks-node
          image: [YOUR-AWS-SUBSCRIPTION-ID].dkr.ecr.us-east-2.amazonaws.com/eksdemoecr:v1
          ports:
            - containerPort: 80